
project_id = "hrcclfajniauohxktykg"
[api]
enabled = true
[db]
shadow_database_url = ""
[realtime]
enabled = true
[studio]
enabled = true
port = 8082
[analytics]
enabled = false
[storage]
enabled = true
[auth]
enabled = true
[auth.email]
enabled = true
double_confirm_changes = true
enable_confirmations = false
[auth.sms]
enabled = false
[functions]
[functions.send-recipe-email]
verify_jwt = false
[functions.generate-recipe]
verify_jwt = false
[functions.generate-recipe-image]
verify_jwt = false
[functions.uploads]
verify_jwt = false
[edge_functions]
[cdn]
[inbucket]
enabled = false
